title: AFD Prototypes
email: david.morris@bbc.co.uk
description: N/A
baseurl: "/tv-navigation-prototype" # the subpath of your site, e.g. /blog
# host: 0.0.0.0


collections:
  prototypes:
    output: true
    permalink: prototypes/:path/

url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: monotonemorris
github_username:  dave-morris

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
